name: Run Hello World Script

on:
  schedule:
    - cron: '15 12 * * *'  # Planifie l'exécution tous les jours à 12h15 UTC
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Utilisation de la version v3

    - name: Set up Python
      uses: actions/setup-python@v3  # Utilisation de la version v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Hello World Script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Accès au secret
      run: |
        python jour.py
