name: Run Selenium Script

on:
  schedule:
    - cron: '15 12 * * *'  # Planifie l'exécution tous les jours à 12h15 UTC
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests

    - name: Run Selenium Script
      run: |
        python ton_fichier_script.py  # Remplace par le nom de ton script

    - name: Upload ChromeDriver logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: chromedriver-log
        path: chromedriver.log
