name: Run Selenium Script

on:
  schedule:
    - cron: '15 12 * * *'  # Planifie l'exécution tous les jours à 12h15 UTC
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests

    - name: Run Selenium Script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        HA_TOKEN: ${{ secrets.HA_TOKEN }}
      run: |
        python jour.py

    - name: Upload HTML page source as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: page-source-html
        path: page_source.html
